### ISSUE TITLE
Wheels for macOS x86_64

### ISSUE THREAD

**Issue by normanrz** [seung-lab/fastremap#39]
Would it be possible to create new wheels with numpy 2 compatibility? The ABI of numpy has changed and importing fastremap doesn't work anymore.
```
>>> import fastremap

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fastremap.pyx", line 1, in init fastremap
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

**Comment by normanrz** [comment]
After debugging a bit, I found that I still have 1.14.0. I am running Python on my Mac with Rosetta (x84_64) but there are no fastremap wheels. I opened #40.

**Comment by william-silversmith** [comment]
New wheels are now released! Thank you!
